# Generated by Django 3.1.7 on 2021-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_author_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(),
        ),
    ]
